version: "3.4"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.4.1"
    hostname: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=0.0.0.0"
      - "cluster.name=wellcome"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"

  common:
    build:
      context: .
      dockerfile: ./common/Dockerfile
  ingestor:
    build:
      context: .
      dockerfile: ./ingestor/Dockerfile
    ports:
      - "9001:8080"
    environment:
      - "AWS_LAMBDA_FUNCTION_TIMEOUT=600"
      - "APP_CONTEXT=docker-compose"
  aggregator:
    build:
      context: .
      dockerfile: ./aggregator/Dockerfile
      target: sqs_lambda
    ports:
      - "9000:8080"
    environment:
      - "APP_CONTEXT=docker-compose"
  aggregator-bulk:
    build:
      context: .
      dockerfile: ./aggregator/Dockerfile
      target: bulk_lambda
    ports:
      - "9002:8080"
    environment:
      - "APP_CONTEXT=docker-compose"
  recorder:
    build:
      context: .
      dockerfile: ./recorder/Dockerfile
      target: sqs_lambda
    ports:
      - "9003:8080"
    environment:
      - "APP_CONTEXT=docker-compose"
  recorder_bulk:
    build:
      context: .
      dockerfile: ./recorder/Dockerfile
      target: bulk_lambda
    ports:
      - "9004:8080"
    environment:
      - "APP_CONTEXT=docker-compose"
