version: "3.4"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.4.1"
    hostname: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=0.0.0.0"
      - "cluster.name=wellcome"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"

  common:
    build:
      context: .
      dockerfile: ./common/Dockerfile
  ingestor:
    build:
      context: .
      dockerfile: ./ingestor/Dockerfile
  aggregator:
    build:
      context: .
      dockerfile: ./aggregator/Dockerfile
    ports:
      - "9000:8080"
    environment:
      - "AGGREGATOR_APP_CONTEXT=docker-compose"
