steps:
  - label: "autoformat"
    command: .buildkite/scripts/autoformat.sh
    agents:
      queue: "nano"
  - label: "ingestor"
    command: |
      .buildkite/scripts/run_sbt_job.sh ingestor
    plugins:
      - ecr#v2.1.1:
          login: true
    agents:
      queue: "scala"
