steps:
  - label: "autoformat"
    command: .buildkite/scripts/autoformat.sh
    agents:
      queue: "nano"

  - label: "test: ingestor"
    command: "test"
    plugins:
      - docker-compose#v3.10.0:
          config:
            - docker-compose.yml
            - docker-compose.test.yml
          run: ingestor
    agents:
      queue: "scala"

  - label: "publish: ingestor"
    branches: "ingestor-ecr" # Change to main
    plugins:
      - ecr#v2.5.0:
          login: true
      - docker-compose#v3.10.0:
          push:
            - ingestor:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_ingestor:ref.${BUILDKITE_COMMIT}
            - ingestor:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_ingestor:latest
    agents:
      queue: "scala"
