env:
  LIVE_PIPELINE: 2022-08-31
steps:
  - label: "autoformat"
    command: .buildkite/scripts/autoformat.sh
    agents:
      queue: "nano"

  - label: "test: common"
    plugins:
      - docker-compose#v3.10.0:
          config:
            - docker-compose.yml
          run: common
          command: ["test"]
    agents:
      queue: "scala"

  - label: "test: ingestor"
    plugins:
      - docker-compose#v3.10.0:
          config:
            - docker-compose.yml
            - docker-compose.test.yml
          run: ingestor
          command: ["test"]
    agents:
      queue: "scala"

  - label: "test: aggregator"
    plugins:
      - docker-compose#v3.10.0:
          config:
            - docker-compose.yml
            - docker-compose.test.yml
          run: aggregator
          command: ["test"]
    agents:
      queue: "scala"

  - label: "test: recorder"
    plugins:
      - docker-compose#v3.10.0:
          config:
            - docker-compose.yml
            - docker-compose.test.yml
          run: recorder
          command: ["test"]
    agents:
      queue: "scala"

  - wait

  - label: "publish: ingestor"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.5.0:
          login: true
      - docker-compose#v3.10.0:
          push:
            - ingestor:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_ingestor:ref.${BUILDKITE_COMMIT}
            - ingestor:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_ingestor:${LIVE_PIPELINE}
            - ingestor:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_ingestor:latest
    agents:
      queue: "scala"

  - label: "publish: aggregator"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.5.0:
          login: true
      - docker-compose#v3.10.0:
          push:
            - aggregator:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_aggregator:ref.${BUILDKITE_COMMIT}
            - aggregator:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_aggregator:${LIVE_PIPELINE}
            - aggregator:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_aggregator:latest
    agents:
      queue: "scala"

  - label: "publish: aggregator-bulk"
    branches:
      - "main"
      - "bulk-aggregate"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.5.0:
          login: true
      - docker-compose#v3.10.0:
          push:
            - aggregator-bulk:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_aggregator_bulk:ref.${BUILDKITE_COMMIT}
            - aggregator-bulk:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_aggregator_bulk:${LIVE_PIPELINE}
            - aggregator-bulk:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_aggregator_bulk:latest
    agents:
      queue: "scala"

  - label: "publish: recorder"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.5.0:
          login: true
      - docker-compose#v3.10.0:
          push:
            - recorder:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_recorder:ref.${BUILDKITE_COMMIT}
            - recorder:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_recorder:${LIVE_PIPELINE}
            - recorder:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_recorder:latest
    agents:
      queue: "scala"

  - wait

  - label: "deploy aggregator to live pipeline"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
    commands:
      - sh .buildkite/scripts/deploy.sh ${LIVE_PIPELINE} "concepts_aggregator" ${BUILDKITE_COMMIT}

  - label: "deploy aggregator-bulk to live pipeline"
    branches:
      - "main"
      - "bulk-aggregate"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
    commands:
      - sh .buildkite/scripts/deploy.sh ${LIVE_PIPELINE} "concepts_aggregator-bulk" ${BUILDKITE_COMMIT}


  - label: "deploy ingestor to live pipeline"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
    commands:
      - sh .buildkite/scripts/deploy.sh ${LIVE_PIPELINE} "concepts_ingestor" ${BUILDKITE_COMMIT}
      - -
  - label: "deploy recorder to live pipeline"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
    commands:
      - sh .buildkite/scripts/deploy.sh ${LIVE_PIPELINE} "concepts_recorder" ${BUILDKITE_COMMIT}
