env:
  LIVE_PIPELINE: 2022-08-31
steps:
  - label: "autoformat"
    command: .buildkite/scripts/autoformat.sh
    agents:
      queue: "nano"

  - label: "test: common"
    plugins:
      - docker-compose#v3.10.0:
          config:
            - docker-compose.yml
          run: common
          command: ["test"]
    agents:
      queue: "scala"

  - label: "test: ingestor"
    plugins:
      - docker-compose#v3.10.0:
          config:
            - docker-compose.yml
            - docker-compose.test.yml
          run: ingestor
          command: ["test"]
    agents:
      queue: "scala"

  - label: "test: aggregator"
    plugins:
      - docker-compose#v3.10.0:
          config:
            - docker-compose.yml
            - docker-compose.test.yml
          run: aggregator
          command: ["test"]
    agents:
      queue: "scala"

  - wait

  - label: "publish: ingestor"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.5.0:
          login: true
      - docker-compose#v3.10.0:
          push:
            - ingestor:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_ingestor:ref.${BUILDKITE_COMMIT}
            - ingestor:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_ingestor:latest
    agents:
      queue: "scala"

  - label: "publish: aggregator"
    branches:
      - "main"
      - "deploy"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.5.0:
          login: true
      - docker-compose#v3.10.0:
          push:
            - aggregator:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_aggregator:ref.${BUILDKITE_COMMIT}
            - aggregator:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_aggregator:latest
            - aggregator:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_aggregator:${LIVE_PIPELINE}
    agents:
      queue: "scala"

  - wait

  - label: "deploy to live pipeline"
    branches: "deploy"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
    commands:
      - sh .buildkite/scripts/deploy_to_live.sh ${BUILDKITE_COMMIT}
