env:
  LIVE_PIPELINE: 2022-08-31
steps:
  - label: "autoformat"
    command: .buildkite/scripts/autoformat.sh
    agents:
      queue: "nano"

  - label: "test: {{matrix}}"
    plugins:
      - docker-compose#v3.10.0:
          config:
            - docker-compose.yml
          run: common
          command: ["test"]
    agents:
      queue: "scala"
    matrix:
      - "common"
      - "ingestor"
      - "aggregator"
      - "recorder"

  - wait

  - label: "publish: {{matrix}}"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.5.0:
          login: true
      - docker-compose#v3.10.0:
          push:
            - ingestor:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_{{matrix}}:ref.${BUILDKITE_COMMIT}
            - ingestor:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_{{matrix}}:${LIVE_PIPELINE}
            - ingestor:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/concepts_{{matrix}}:latest
    agents:
      queue: "scala"
    matrix:
      - "ingestor"
      - "aggregator"
      - "aggregator_bulk"
      - "recorder"

  - wait

  - label: "deploy {{matrix}} to live pipeline"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
    commands:
      - sh .buildkite/scripts/deploy.sh ${LIVE_PIPELINE} "{{matrix}}" ${BUILDKITE_COMMIT}
    matrix:
      - "ingestor"
      - "aggregator"
      - "aggregator_bulk"
      - "recorder"
